sudo: required
services:
  - docker

before_install:
  - docker build -t clovisrodriguez/portfolio -f Dockerfile.dev .

script:
  - docker run clovisrodriguez/portfolio npm run test -- --coverage

deploy:
  provider: elasticbeanstalk
  region: 'us-east-2'
  app: 'portfolio'
  env: 'Portfolio-env'
  bucket_name: 'elasticbeanstalk-us-east-2-185874895674'
  bucket_path: 'portfolio'
  on:
    branch: master
  access_key_id: $AWS_ACCESS_KEY
  secret_access_key:
    secur: '$AWS_SECRET_KEY'
